### ISSUE TITLE
[List View] Add an option to show feeds icon

### ISSUE THREAD

**Issue by githieu** [qms-apps/Pluma-Android-Issue-Tracker#12]
It would be nice to have a setting to show feed icon in List view.

This visual marker makes it easier to identify the source of an article, especially when the list is long, without having to read the name.

![PlumaFeedsIconsInList](https://user-images.githubusercontent.com/17873299/112639446-8d9f2380-8e40-11eb-9d6b-37b868ffd09e.png)

**Comment by qijaz221** [comment]
This is now available in the latest test versions.
