### ISSUE TITLE
Feed articles list header improvements (Icon + number of articles)

### ISSUE THREAD

**Issue by githieu** [qms-apps/Pluma-Android-Issue-Tracker#15]
In Feed articles list header improvements, would it be possible to add feed icon on the left of feed name and number of articles on the right?

![photo_2021-06-14 13 54 42](https://user-images.githubusercontent.com/17873299/121888499-5e4dd380-cd18-11eb-9a2e-8e66f861d689.jpeg)

**Comment by qijaz221** [comment]
This is now available in the latest version.
