### ISSUE TITLE
[bug] CustomTab doesn't show the system default browser

### ISSUE THREAD

**Issue by coreequip** [qms-apps/Pluma-Android-Issue-Tracker#23]
When tabbing a link or opening a story in a "_CustomTab_" (a.k.a In-App Browser), Pluma™ shows the Chrome browser. On my system the Firefox browser is set up as system default.

Expected behaviour is that the _CustomTab_ shows the Firefox browser instead.

More information [here](https://developer.chrome.com/docs/android/custom-tabs/integration-guide/).

**Comment by qijaz221** [comment]
Added in 1.1.5 alpha.
