### ISSUE TITLE
Feature request - Translate option in context menu

### ISSUE THREAD

**Issue by synergic777** [qms-apps/Pluma-Android-Issue-Tracker#26]
A lot of android apps have integrated translate option in the text selection/context menu. Could you implement this option to the Pluma reader? (It is a shortcut to Google translator)

Example:

![Screenshot_20211124-133547](https://user-images.githubusercontent.com/64419373/143239910-27fb7913-e04f-4210-8a04-2ed16c9ef035.png)

![Screenshot_20211124-133820](https://user-images.githubusercontent.com/64419373/143239989-0f208279-96cd-4d54-a7d6-2e6b74ee7da3.png)

**Comment by qijaz221** [comment]
This should be available in 1.5.9.

**Comment by qijaz221** [comment]
Available in latest version.
