### ISSUE TITLE
Status bar bug

### ISSUE THREAD

**Issue by Kaiser-14** [qms-apps/Pluma-Android-Issue-Tracker#3]
After double tap to full screen, the status bar is coloured black. I have to scroll up from nav bar to really see transparent status bar and full screen. I think full screen mode should hide status bar.

Also after scroll up the nav bar, the bar appears and I do not know it was your plan.

Android version: Android 11
App version: 0.5.3 beta

**Comment by PrithirajN** [comment]
For me the nav bar do not turn transparent, it remains as a black bar.

**Comment by qijaz221** [comment]
Closing as this should be fixed now.
