### ISSUE TITLE
Global keyword filters

### ISSUE THREAD

**Issue by qijaz221** [qms-apps/Pluma-Android-Issue-Tracker#32]
Add option to set global keyword filters instead of per feed basis.

**Comment by darrenmcentee** [comment]
Importing a list would be very handy too, like CSV.
i keep a list, words and phrases, that i dont want. Importing this list would be great.

**Comment by darrenmcentee** [comment]
Any idea when this might be implemented?

**Comment by qijaz221** [comment]
This is available in 1.4.7, though we still don't have CSV import.
