### ISSUE TITLE
Pluma still showing empty Inoreader "Folders"

### ISSUE THREAD

**Issue by darrenmcentee** [qms-apps/Pluma-Android-Issue-Tracker#38]
Just noticed when testing, that when you add a new Folder in Inoreader web, and add one feed to it, it updates this ok on Pluma.
But again in Inoreader web, when I moved a feed from one folder to another, the empty folder still stays in Pluma.
I attach a screeshot. 
![Screenshot_2](https://user-images.githubusercontent.com/2485782/154671831-4625d4ea-4d69-4f45-9243-e74bb450138b.jpg)

Folders "test" and "uncategorized" do not exist in Inoreader, as they don't contain any feeds.
Looks like the folder sync between Inoreader and Pluma isnt updating the folders.
Thanks.

**Comment by qijaz221** [comment]
Fixed in 1.4.8, reopen if required after the update.
