### ISSUE TITLE
Categories improvements

### ISSUE THREAD

**Issue by githieu** [qms-apps/Pluma-Android-Issue-Tracker#9]
It would be nice to be able to rearrange the order of the categories, which would then be used in the filter bar. 
In the same way it could be nice to let user choose the color of each category and use these colors in filter bar for selected categories (instead of blue)

![PlumaCategoriesSorting](https://user-images.githubusercontent.com/17873299/112627837-68a3b400-8e32-11eb-8af9-54b9eb1e4bd0.png)

**Comment by qijaz221** [comment]
This is now available in the latest versions except the color option since we don't use any color to represent a category.
